#!/bin/bash
set -euo pipefail

# Usage: ./sync-to-repo.sh USER/target-repo [config-repo] [config-branch]
#
# Environment:
#   GH_TOKEN or GITHUB_TOKEN - GitHub token (required)

if [ $# -lt 1 ]; then
  echo "Usage: $0 USER/target-repo [config-repo] [config-branch]"
  exit 1
fi

TARGET_REPO="$1"
CONFIG_REPO="${2:-USER/claude-config}"
CONFIG_BRANCH="${3:-main}"
WORK_DIR=$(mktemp -d)
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="update-config-${TIMESTAMP}"

# Cleanup on exit
trap 'rm -rf "$WORK_DIR"' EXIT

echo "🔧 Syncing config to ${TARGET_REPO}..."
echo "📦 Config source: ${CONFIG_REPO}@${CONFIG_BRANCH}"
echo "💼 Working directory: ${WORK_DIR}"

cd "$WORK_DIR"

# Clone both repos using HTTPS with token authentication
echo "📥 Cloning repositories..."
git clone --depth 1 --branch "$CONFIG_BRANCH" --single-branch \
  "https://x-access-token:${GH_TOKEN}@github.com/${CONFIG_REPO}.git" config
git clone --depth 1 \
  "https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git" target

# Ensure target has .claude directory
mkdir -p target/.claude

# Copy all config files
echo "📋 Copying .claude files..."
cp -r config/.claude/* target/.claude/

# Check if anything changed (including new untracked files)
cd target
git add .claude/
if git diff --cached --quiet .claude/; then
  echo "✅ No changes detected - already up to date"
  exit 0
fi

# Show what changed
echo ""
echo "📊 Changes detected:"
git diff --cached --stat .claude/
echo ""

# Create branch and commit (files already staged from check above)
echo "🌿 Creating branch: ${BRANCH_NAME}"
git checkout -b "$BRANCH_NAME"

git commit -m "chore(config): update Claude config

Updated configuration from ${CONFIG_REPO}.

🤖 Generated with Claude Code
Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"

# Push branch
echo "⬆️  Pushing branch to origin..."
git push -u origin "$BRANCH_NAME"

# Create PR
echo "🔀 Creating pull request..."
PR_URL=$(gh pr create \
  --head "$BRANCH_NAME" \
  --title "chore(config): update Claude config" \
  --body "## 🛡️ Config Update

**Source:** [${CONFIG_REPO}](https://github.com/${CONFIG_REPO})
**Branch:** \`${CONFIG_BRANCH}\`

### 📊 Changes

\`\`\`
$(git diff --stat HEAD~1 .claude/)
\`\`\`

### 📝 Files Updated

\`\`\`
$(git diff --name-only HEAD~1 .claude/)
\`\`\`

### ✅ Review Checklist

- [ ] Review hookify rule changes
- [ ] Check settings.json permissions
- [ ] Verify no project-specific configs overwritten
- [ ] Test rules don't break development workflow

---

🤖 Auto-generated by [sync-to-repo.sh](https://github.com/${CONFIG_REPO}/blob/main/sync-to-repo.sh)" \
  --label "config,dependencies,automated")

echo ""
echo "✅ Done! Pull request created:"
echo "   ${PR_URL}"
