name: Bug Report
description: Report something that isn't working correctly
title: "fix(scope): "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Use this template to report bugs or issues.
        Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's broken?
      placeholder: Brief description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what you observed
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Affected Area
      description: What part of the cluster is affected?
      options:
        - Claude Config (.claude/)
        - Claude Agents (.claude/agents)
        - Claude Rules (.claude/rules)
        - Documentation
        - CI/CD (.github/)
        - Other
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Logs/Evidence
      description: Relevant logs, error messages, or screenshots
      placeholder: |
        ```
        Paste logs here (redact any secrets!)
        ```
      render: shell
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a temporary workaround?
      placeholder: Describe any workaround you've found
    validations:
      required: false

  - type: textarea
    id: related
    attributes:
      label: Related Issues/PRs
      description: Link any related issues or PRs
      placeholder: |
        - #123
        - #456
    validations:
      required: false
