name: Documentation
description: Documentation updates, additions, or improvements
title: "docs(scope): "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Task

        Use this template for documentation work: new docs, updates, fixes, or reorganization.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What documentation work is needed?
      placeholder: Brief description of the documentation change
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this documentation needed or outdated?
      placeholder: What problem does this solve? What's missing or incorrect?
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What kind of documentation work is this?
      options:
        - New documentation
        - Update existing docs
        - Fix errors/typos
        - Reorganize/restructure
        - Add examples
        - API/reference docs
        - Runbook/procedure
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Affected Area
      description: What part of the system does this document?
      options:
        - Claude Config (.claude/)
        - Claude Agents (.claude/agents)
        - Claude Rules (.claude/rules)
        - CI/CD (.github/)
        - General/README
        - Other
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: Files to Create/Update
      description: Which documentation files will be affected?
      placeholder: |
        - docs/new-guide.md
        - README.md
    validations:
      required: false

  - type: textarea
    id: outline
    attributes:
      label: Content Outline
      description: What should the documentation cover?
      placeholder: |
        - Section 1: Overview
        - Section 2: Setup steps
        - Section 3: Examples
    validations:
      required: false

  - type: textarea
    id: related
    attributes:
      label: Related Issues/PRs
      description: Link any related issues or PRs
      placeholder: |
        - #123
        - #456
    validations:
      required: false
