name: Feature Request
description: Propose a new feature or enhancement
title: "feat(scope): "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Use this template to propose new features or enhancements.
        Please fill out all required fields.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the feature
      placeholder: What do you want to add or change?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
      placeholder: What problem does this solve? What use case does it enable?
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Affected Area
      description: What part of the cluster does this affect?
      options:
        - Claude Config (.claude/)
        - Claude Agents (.claude/agents)
        - Claude Rules (.claude/rules)
        - CI/CD (.github/)
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any technical details, constraints, or suggestions
      placeholder: Optional notes about implementation approach
    validations:
      required: false

  - type: textarea
    id: testing
    attributes:
      label: Testing Plan
      description: How should this feature be tested?
      placeholder: |
        - [ ] Test case 1
        - [ ] Test case 2
    validations:
      required: false

  - type: textarea
    id: related
    attributes:
      label: Related Issues/PRs
      description: Link any related issues or PRs
      placeholder: |
        - #123
        - #456
    validations:
      required: false
